# Change these first
owner: NatanaelGeraldoS # Your GitHub organization or username, where this repository lives
repo: BINUSWeb # The name of this repository

sites:
  - name: Student Desk BINUS SCHOOL Serpong
    url: https://serpong.binus-school.net/student/LoginBinusian.aspx
  - name: Parent Desk BINUS SCHOOL Serpong
    url: https://serpong.binus-school.net/parent/LoginBinusian.aspx
  - name: Staff Desk BINUS SCHOOL Serpong
    url: https://serpong.binus-school.net/staffdesk/LoginBinusian.aspx
  - name: LRC BINUS SCHOOL Serpong
    url: http://serpong.binus-school.net/Library/
  - name: Beelajar
    url: https://beelajar.apps.binus.edu/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /BINUSWeb
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BINUSWeb
  introTitle: "UpTime Website BINUS"
  introMessage: Monitoring UpTime dari Website BINUS
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
